# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ba046d074f8123cf6e6cf92a41717e21ddba551fac582c6299d37116b1c8656a0e2345a824b9f52ef9625d1d43a70f4325fd15552fb5d04d5c727bb50dbd348

test:
  secret_key_base: 3604d5d652bc3e616fcd8f29043000d7d94d880eb44d6d73dec0a7c984ead1a6e0fb8e6c8c980fb59e392896d2e0a88f13b5452414f862eadb05c9fc14ca77c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
